//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takhfif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Products = new HashSet<Product>();
            this.Slides = new HashSet<Slide>();
            this.Uploads = new HashSet<Upload>();
            this.Posts = new HashSet<Post>();
            this.Finilizations = new HashSet<Finilization>();
        }
    

    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Slide> Slides { get; set; }
        public virtual ICollection<Upload> Uploads { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Finilization> Finilizations { get; set; }
    }
}
